services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marothi-portfolio
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/portfolio.db;Cache=Shared"
      AdminUser__Email: "admin@marothimohale.dev"
      AdminUser__Password: "MarothiAdmin1"
    volumes:
      - portfolio-data:/app/data

volumes:
  portfolio-data:
